In [11]:
import numpy as np
import pandas as pd 
import scipy.sparse

import random

In [15]:
imgs = np.arange(10000)
randoms = np.random.uniform(size=10000)
classes = np.zeros(imgs.shape[0])
classes[randoms > 0.8] = 1
class_imgs = {
    0: imgs[np.where(classes == 0)],
    1: imgs[np.where(classes == 1)]
}


In [16]:
np.unique(classes, return_counts=True)

(array([ 0.,  1.]), array([8064, 1936]))

In [17]:
imgs[np.where(classes == 1)]

array([   0,    1,    3, ..., 9955, 9968, 9987])

In [22]:
pairs = []

def random_pair_of_class(cl):
    imgs = class_imgs[cl]
    return imgs[random.randint(0, len(imgs)-1)], imgs[random.randint(0, len(imgs)-1)]

for i in range(int(14 * len(imgs) / 2)):
    pairs.append(random_pair_of_class(0))
    pairs.append(random_pair_of_class(1))

pairs = np.array(pairs)

In [23]:
pairs

array([[1315, 6643],
       [6465, 1870],
       [2312, 8026],
       ..., 
       [1870, 4794],
       [8304, 3472],
       [3838, 5860]])

In [24]:
from scipy.sparse import coo_matrix

mat_rows = pairs[:,0]
mat_cols = pairs[:,1]

In [26]:
mat_rows

array([1315, 6465, 2312, ..., 1870, 8304, 3838])

In [27]:
inc_mat = coo_matrix((np.ones(len(mat_cols)), (mat_rows, mat_cols))) + coo_matrix((np.ones(len(mat_cols)), (mat_cols, mat_rows)))
inc_mat[inc_mat > 1] = 1

In [28]:
inc_mat.max()

1.0

In [29]:
inc_mat.sum()

277096.0

In [30]:
len(pairs)

140000

In [31]:
inc_mat = inc_mat.tocsr()

In [32]:
rows_first = inc_mat[pairs[:,0]]
rows_second = inc_mat[pairs[:,1]]
f = np.sum(rows_first.multiply(rows_second), axis=1)
f = np.squeeze(np.asarray(f))

In [33]:
f

array([ 0.,  5.,  0., ...,  2.,  0.,  2.])

In [35]:
for i in sorted(list(zip(*np.unique(f, return_counts=True))), key=lambda x:x[1], reverse=True):
   print("{:4d} {:5d}".format(int(i[0]), i[1]))

   0 72404
   2 17576
   1 16024
   3 15232
   4  9906
   5  5250
   6  2310
   7   842
   8   287
   9    95
  10    21
  11     4
  72     4
  59     3
  68     3
  70     3
  74     3
  77     3
  83     3
  60     2
  62     2
  63     2
  73     2
  75     2
  76     2
  82     2
  16     1
  18     1
  21     1
  24     1
  64     1
  66     1
  67     1
  69     1
  71     1
  79     1
  81     1
  87     1
  92     1


In [47]:
imgs = np.arange(10000)
randoms = np.random.uniform(size=imgs.shape[0])
classes = np.zeros(imgs.shape[0])
classes[randoms > 0.999] = 1
class_imgs = {
    0: imgs[np.where(classes == 0)],
    1: imgs[np.where(classes == 1)]
}

pairs = []

def random_pair_of_class(cl):
    imgs = class_imgs[cl]
    return imgs[random.randint(0, len(imgs)-1)], imgs[random.randint(0, len(imgs)-1)]

for i in range(int(380000 / 2)):
    pairs.append(random_pair_of_class(0))
    pairs.append(random_pair_of_class(1))

pairs = np.array(pairs)

from scipy.sparse import coo_matrix

mat_rows = pairs[:,0]
mat_cols = pairs[:,1]

inc_mat = coo_matrix((np.ones(len(mat_cols)), (mat_rows, mat_cols))) + coo_matrix((np.ones(len(mat_cols)), (mat_cols, mat_rows)))
inc_mat[inc_mat > 1] = 1

rows_first = inc_mat[pairs[:,0]]
rows_second = inc_mat[pairs[:,1]]
f = np.sum(rows_first.multiply(rows_second), axis=1)
f = np.squeeze(np.asarray(f))

for i in sorted(list(zip(*np.unique(f, return_counts=True))), key=lambda x:x[1], reverse=True):
   print("{:4d} {:5d}".format(int(i[0]), i[1]))

  13 190000
   0 163688
   1 24452
   2  1742
   3    95
   4     3
  38     3
  41     2
  42     2
  48     2
  29     1
  30     1
  31     1
  32     1
  33     1
  34     1
  35     1
  37     1
  39     1
  44     1
  53     1
